sudo: required
services:
  - docker

script:
  - docker build -t nikzadb/react-example .
  - docker images nikzadb/react-example

before_deploy:
  - docker login -u nikzad -p Ryan2010
  - docker images nikzadb/react-example

deploy:
  - provider: script
  - script: docker push nikzad/react-example
  on:
    branch: master

